export const endpoints = {
  auth: {
    login: "/api/auth/login",
    me: "/api/auth/me",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
    logout: "/api/auth/logout",
    refresh: "/api/auth/refresh",
  },
  admin: {
    dashboard: "/api/admin/stats",
    proxyStatus: "/api/admin/proxy/status",
    usersStats: "/api/admin/users/stats",
    users: "/api/admin/users",
    userDetail: (id: string) => `/api/admin/users/${id}`,
    userServices: (id: string) => `/api/admin/users/${id}/services`,
    userRouters: (id: string) => `/api/admin/users/${id}/routers`,
    userBilling: (id: string) => `/api/admin/users/${id}/billing`,
    userActivity: (id: string) => `/api/admin/users/${id}/activity`,
    userSecurity: (id: string) => `/api/admin/users/${id}/security`,
    userSupport: (id: string) => `/api/admin/users/${id}/support`,
    userNotes: (id: string) => `/api/admin/users/${id}/notes`,
    userFlags: (id: string) => `/api/admin/users/${id}/flags`,
    suspendUser: (id: string) => `/api/admin/users/${id}/suspend`,
    reactivateUser: (id: string) => `/api/admin/users/${id}/reactivate`,
    verifyUser: (id: string) => `/api/admin/users/${id}/verify`,
    resendVerification: (id: string) => `/api/admin/users/${id}/resend-verification`,
    sendPasswordReset: (id: string) => `/api/admin/users/${id}/send-password-reset`,
    forceLogoutUser: (id: string) => `/api/admin/users/${id}/force-logout`,
    extendUserTrial: (id: string) => `/api/admin/users/${id}/extend-trial`,
    addUserNote: (id: string) => `/api/admin/users/${id}/notes`,
    flagUser: (id: string) => `/api/admin/users/${id}/flags`,
    removeUserFlag: (id: string, flagId: string) => `/api/admin/users/${id}/flags/${flagId}`,
    routerStats: "/api/admin/routers/stats",
    routers: "/api/admin/routers",
    routerDetail: (id: string) => `/api/admin/routers/${id}`,
    routerConnectivity: (id: string) => `/api/admin/routers/${id}/connectivity`,
    routerPorts: (id: string) => `/api/admin/routers/${id}/ports`,
    routerMonitoring: (id: string) => `/api/admin/routers/${id}/monitoring`,
    routerActivity: (id: string) => `/api/admin/routers/${id}/activity`,
    routerProvisioning: (id: string) => `/api/admin/routers/${id}/provisioning`,
    routerDiagnostics: (id: string) => `/api/admin/routers/${id}/diagnostics`,
    routerNotes: (id: string) => `/api/admin/routers/${id}/notes`,
    routerFlags: (id: string) => `/api/admin/routers/${id}/flags`,
    disableRouter: (id: string) => `/api/admin/routers/${id}/disable`,
    reactivateRouter: (id: string) => `/api/admin/routers/${id}/reactivate`,
    reprovisionRouter: (id: string) => `/api/admin/routers/${id}/reprovision`,
    regenerateRouterSetup: (id: string) => `/api/admin/routers/${id}/regenerate-setup`,
    resetRouterPeer: (id: string) => `/api/admin/routers/${id}/reset-peer`,
    reassignRouterPorts: (id: string) => `/api/admin/routers/${id}/reassign-ports`,
    moveRouterServer: (id: string) => `/api/admin/routers/${id}/move-server`,
    markRouterReviewed: (id: string) => `/api/admin/routers/${id}/mark-reviewed`,
    removeRouterFlag: (id: string, flagId: string) => `/api/admin/routers/${id}/flags/${flagId}`,
    deleteRouter: (id: string) => `/api/admin/routers/${id}`,
    vpnServersStats: "/api/admin/vpn-servers/stats",
    vpnServers: "/api/admin/vpn-servers",
    vpnServerDetail: (id: string) => `/api/admin/vpn-servers/${id}`,
    vpnServerHealth: (id: string) => `/api/admin/vpn-servers/${id}/health`,
    vpnServerRouters: (id: string) => `/api/admin/vpn-servers/${id}/routers`,
    vpnServerPeers: (id: string) => `/api/admin/vpn-servers/${id}/peers`,
    vpnServerTraffic: (id: string) => `/api/admin/vpn-servers/${id}/traffic`,
    vpnServerActivity: (id: string) => `/api/admin/vpn-servers/${id}/activity`,
    vpnServerDiagnostics: (id: string) => `/api/admin/vpn-servers/${id}/diagnostics`,
    vpnServerNotes: (id: string) => `/api/admin/vpn-servers/${id}/notes`,
    vpnServerFlags: (id: string) => `/api/admin/vpn-servers/${id}/flags`,
    addVpnServer: "/api/admin/vpn-servers",
    disableVpnServer: (id: string) => `/api/admin/vpn-servers/${id}/disable`,
    reactivateVpnServer: (id: string) => `/api/admin/vpn-servers/${id}/reactivate`,
    enableServerMaintenance: (id: string) => `/api/admin/vpn-servers/${id}/maintenance`,
    clearServerMaintenance: (id: string) => `/api/admin/vpn-servers/${id}/maintenance/clear`,
    migrateServerRouters: (id: string) => `/api/admin/vpn-servers/${id}/migrate-routers`,
    restartServerVpn: (id: string) => `/api/admin/vpn-servers/${id}/restart-vpn`,
    reconcileVpnServer: (id: string) => `/api/admin/vpn-servers/${id}/reconcile`,
    markVpnServerReviewed: (id: string) => `/api/admin/vpn-servers/${id}/mark-reviewed`,
    removeVpnServerFlag: (id: string, flagId: string) => `/api/admin/vpn-servers/${id}/flags/${flagId}`,
    monitoringOverview: "/api/admin/monitoring/overview",
    monitoringTrends: "/api/admin/monitoring/trends",
    monitoringActivity: "/api/admin/monitoring/activity",
    monitoringDiagnostics: "/api/admin/monitoring/diagnostics",
    monitoringRouterSummary: "/api/admin/monitoring/routers/summary",
    monitoringRoutersUnhealthy: "/api/admin/monitoring/routers/unhealthy",
    monitoringRoutersOffline: "/api/admin/monitoring/routers/offline",
    monitoringRoutersProvisioningIssues: "/api/admin/monitoring/routers/provisioning-issues",
    monitoringRoutersStale: "/api/admin/monitoring/routers/stale",
    monitoringVpnServerSummary: "/api/admin/monitoring/vpn-servers/summary",
    monitoringVpnServersUnhealthy: "/api/admin/monitoring/vpn-servers/unhealthy",
    monitoringVpnServersOverloaded: "/api/admin/monitoring/vpn-servers/overloaded",
    monitoringVpnServersStale: "/api/admin/monitoring/vpn-servers/stale",
    monitoringPeerSummary: "/api/admin/monitoring/peers/summary",
    monitoringPeersStale: "/api/admin/monitoring/peers/stale",
    monitoringPeersUnhealthy: "/api/admin/monitoring/peers/unhealthy",
    monitoringTrafficSummary: "/api/admin/monitoring/traffic/summary",
    monitoringTrafficTrends: "/api/admin/monitoring/traffic/trends",
    monitoringTrafficTopRouters: "/api/admin/monitoring/traffic/top-routers",
    monitoringTrafficTopServers: "/api/admin/monitoring/traffic/top-servers",
    monitoringCustomerImpact: "/api/admin/monitoring/customers/impact",
    monitoringAffectedCustomers: "/api/admin/monitoring/customers/affected",
    monitoringProvisioningSummary: "/api/admin/monitoring/provisioning/summary",
    monitoringProvisioningTrends: "/api/admin/monitoring/provisioning/trends",
    monitoringProvisioningFailures: "/api/admin/monitoring/provisioning/failures",
    monitoringIncidents: "/api/admin/monitoring/incidents",
    monitoringIncidentDetail: (id: string) => `/api/admin/monitoring/incidents/${id}`,
    monitoringIncidentNotes: (id: string) => `/api/admin/monitoring/incidents/${id}/notes`,
    acknowledgeMonitoringIncident: (id: string) => `/api/admin/monitoring/incidents/${id}/acknowledge`,
    resolveMonitoringIncident: (id: string) => `/api/admin/monitoring/incidents/${id}/resolve`,
    markMonitoringIncidentReviewed: (id: string) => `/api/admin/monitoring/incidents/${id}/mark-reviewed`,
    billingOverview: "/api/admin/billing/overview",
    billingAnalytics: "/api/admin/billing/analytics",
    billingActivity: "/api/admin/billing/activity",
    billingRisk: "/api/admin/billing/risk",
    billingSubscriptions: "/api/admin/billing/subscriptions",
    billingSubscriptionDetail: (id: string) => `/api/admin/billing/subscriptions/${id}`,
    billingAccountOverview: (id: string) => `/api/admin/billing/accounts/${id}/overview`,
    billingAccountEntitlements: (id: string) => `/api/admin/billing/accounts/${id}/entitlements`,
    billingAccountBillableRouters: (id: string) => `/api/admin/billing/accounts/${id}/billable-routers`,
    billingAccountActivity: (id: string) => `/api/admin/billing/accounts/${id}/activity`,
    billingInvoices: "/api/admin/billing/invoices",
    billingInvoiceDetail: (id: string) => `/api/admin/billing/invoices/${id}`,
    billingAccountInvoices: (id: string) => `/api/admin/billing/accounts/${id}/invoices`,
    billingPayments: "/api/admin/billing/payments",
    billingPaymentDetail: (id: string) => `/api/admin/billing/payments/${id}`,
    billingAccountPayments: (id: string) => `/api/admin/billing/accounts/${id}/payments`,
    billingTrials: "/api/admin/billing/trials",
    billingNotes: (id: string) => `/api/admin/billing/accounts/${id}/notes`,
    billingFlags: (id: string) => `/api/admin/billing/accounts/${id}/flags`,
    billingExtendTrial: (id: string) => `/api/admin/billing/accounts/${id}/extend-trial`,
    billingMarkReviewed: (id: string) => `/api/admin/billing/accounts/${id}/mark-reviewed`,
    billingSuspend: (id: string) => `/api/admin/billing/accounts/${id}/suspend`,
    billingReactivate: (id: string) => `/api/admin/billing/accounts/${id}/reactivate`,
    billingResendInvoice: (id: string) => `/api/admin/billing/accounts/${id}/resend-invoice`,
    billingApplyGracePeriod: (id: string) => `/api/admin/billing/accounts/${id}/apply-grace-period`,
    billingRemoveGracePeriod: (id: string) => `/api/admin/billing/accounts/${id}/remove-grace-period`,
    billingRemoveFlag: (id: string, flagId: string) => `/api/admin/billing/accounts/${id}/flags/${flagId}`,
  },
  users: "/api/users",
  routers: "/api/routers",
  clients: "/api/clients",
  billing: "/api/billing",
  logs: "/api/logs",
  support: "/api/support",
  settings: "/api/settings",
} as const;
