export const endpoints = {
  auth: {
    login: "/api/auth/login",
    loginTwoFactor: "/api/auth/login/2fa",
    me: "/api/auth/me",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
    logout: "/api/auth/logout",
    refresh: "/api/auth/refresh",
  },
  profile: {
    get: "/api/profile",
    update: "/api/profile",
    twoFactorSetup: "/api/profile/2fa/setup",
    twoFactorEnable: "/api/profile/2fa/enable",
    twoFactorDisable: "/api/profile/2fa/disable",
  },
  referrals: {
    code: "/api/referrals/code",
    stats: "/api/referrals/stats",
    list: "/api/referrals",
  },
  admin: {
    dashboard: "/api/admin/stats",
    proxyStatus: "/api/admin/proxy/status",
    usersStats: "/api/admin/users/stats",
    users: "/api/admin/users",
    createUser: "/api/admin/users",
    userDetail: (id: string) => `/api/admin/users/${id}`,
    editUserProfile: (id: string) => `/api/admin/users/${id}`,
    deleteUser: (id: string) => `/api/admin/users/${id}`,
    userServices: (id: string) => `/api/admin/users/${id}/services`,
    userRouters: (id: string) => `/api/admin/users/${id}/routers`,
    userBilling: (id: string) => `/api/admin/users/${id}/billing`,
    userActivity: (id: string) => `/api/admin/users/${id}/activity`,
    userSecurity: (id: string) => `/api/admin/users/${id}/security`,
    userSupport: (id: string) => `/api/admin/users/${id}/support`,
    userNotes: (id: string) => `/api/admin/users/${id}/notes`,
    userFlags: (id: string) => `/api/admin/users/${id}/flags`,
    suspendUser: (id: string) => `/api/admin/users/${id}/suspend`,
    reactivateUser: (id: string) => `/api/admin/users/${id}/reactivate`,
    verifyUser: (id: string) => `/api/admin/users/${id}/verify`,
    resendVerification: (id: string) => `/api/admin/users/${id}/resend-verification`,
    sendPasswordReset: (id: string) => `/api/admin/users/${id}/send-password-reset`,
    forceLogoutUser: (id: string) => `/api/admin/users/${id}/force-logout`,
    extendUserTrial: (id: string) => `/api/admin/users/${id}/extend-trial`,
    addUserNote: (id: string) => `/api/admin/users/${id}/notes`,
    flagUser: (id: string) => `/api/admin/users/${id}/flags`,
    removeUserFlag: (id: string, flagId: string) => `/api/admin/users/${id}/flags/${flagId}`,
    routerStats: "/api/admin/routers/stats",
    routers: "/api/admin/routers",
    routerDetail: (id: string) => `/api/admin/routers/${id}`,
    routerConnectivity: (id: string) => `/api/admin/routers/${id}/connectivity`,
    routerMetrics: (id: string) => `/api/admin/routers/${id}/metrics`,
    routerTopologyDevices: (routerId: string) => `/api/admin/routers/${routerId}/topology/devices`,
    routerTopologyNetwork: (routerId: string) => `/api/admin/routers/${routerId}/topology/network`,
    routerTopologyStats: (routerId: string) => `/api/admin/routers/${routerId}/topology/stats`,
    routerTopologyClusters: (routerId: string, zoom: number) => `/api/admin/routers/${routerId}/topology/clusters?zoom=${zoom}`,
    routerTopologyDiscover: (routerId: string) => `/api/admin/routers/${routerId}/topology/discover`,
    hotspotUsers: (routerId: string) => `/api/admin/routers/${routerId}/hotspot/users`,

    hotspotUser: (routerId: string, userId: string) => `/api/admin/routers/${routerId}/hotspot/users/${userId}`,
    hotspotVouchers: (routerId: string) => `/api/admin/routers/${routerId}/hotspot/vouchers`,
    hotspotSessions: (routerId: string) => `/api/admin/routers/${routerId}/hotspot/sessions`,
    hotspotSession: (routerId: string, sessionId: string) => `/api/admin/routers/${routerId}/hotspot/sessions/${sessionId}`,
    hotspotProfiles: (routerId: string) => `/api/admin/routers/${routerId}/hotspot/profiles`,
    pppoeSecrets: (routerId: string) => `/api/admin/routers/${routerId}/pppoe/secrets`,
    pppoeSecret: (routerId: string, id: string) => `/api/admin/routers/${routerId}/pppoe/secrets/${id}`,
    pppoeSessions: (routerId: string) => `/api/admin/routers/${routerId}/pppoe/sessions`,
    pppoeSession: (routerId: string, id: string) => `/api/admin/routers/${routerId}/pppoe/sessions/${id}`,
    pppoeProfiles: (routerId: string) => `/api/admin/routers/${routerId}/pppoe/profiles`,
    routerQueues: (routerId: string) => `/api/admin/routers/${routerId}/queues`,
    routerQueue: (routerId: string, id: string) => `/api/admin/routers/${routerId}/queues/${id}`,
    routerApplyPlan: (routerId: string) => `/api/admin/routers/${routerId}/queues/apply-plan`,
    firewallFilter: (routerId: string) => `/api/admin/routers/${routerId}/firewall/filter`,
    firewallFilterRule: (routerId: string, ruleId: string) => `/api/admin/routers/${routerId}/firewall/filter/${ruleId}`,
    firewallFilterToggle: (routerId: string, ruleId: string) => `/api/admin/routers/${routerId}/firewall/filter/${ruleId}/toggle`,
    firewallNat: (routerId: string) => `/api/admin/routers/${routerId}/firewall/nat`,
    firewallNatRule: (routerId: string, ruleId: string) => `/api/admin/routers/${routerId}/firewall/nat/${ruleId}`,
    firewallAddressList: (routerId: string) => `/api/admin/routers/${routerId}/firewall/address-list`,
    firewallAddressListEntry: (routerId: string, id: string) => `/api/admin/routers/${routerId}/firewall/address-list/${id}`,
    firewallBlock: (routerId: string) => `/api/admin/routers/${routerId}/firewall/block`,
    firewallUnblock: (routerId: string) => `/api/admin/routers/${routerId}/firewall/unblock`,
    routerDhcpLeases: (id: string) => `/api/admin/routers/${id}/network/dhcp-leases`,
    routerDhcpLease: (id: string, leaseId: string) => `/api/admin/routers/${id}/network/dhcp-leases/${leaseId}`,
    routerWirelessClients: (id: string) => `/api/admin/routers/${id}/network/wireless-clients`,
    routerInterfaces: (id: string) => `/api/admin/routers/${id}/network/interfaces`,
    routerBackups: (id: string) => `/api/admin/routers/${id}/backups`,
    routerBackup: (id: string, backupId: string) => `/api/admin/routers/${id}/backups/${backupId}`,
    routerBackupContent: (id: string, backupId: string) => `/api/admin/routers/${id}/backups/${backupId}/content`,
    routerSetCredentials: (id: string) => `/api/admin/routers/${id}/set-credentials`,
    routerTestConnection: (id: string) => `/api/admin/routers/${id}/test-connection`,
    routerPorts: (id: string) => `/api/admin/routers/${id}/ports`,
    routerMonitoring: (id: string) => `/api/admin/routers/${id}/monitoring`,
    routerActivity: (id: string) => `/api/admin/routers/${id}/activity`,
    routerProvisioning: (id: string) => `/api/admin/routers/${id}/provisioning`,
    routerDiagnostics: (id: string) => `/api/admin/routers/${id}/diagnostics`,
    routerNotes: (id: string) => `/api/admin/routers/${id}/notes`,
    routerFlags: (id: string) => `/api/admin/routers/${id}/flags`,
    routerDownstreamMikrotiks: (id: string) => `/api/admin/routers/${id}/downstream-mikrotiks`,
    routerDiscoverDownstreamMikrotiks: (id: string) => `/api/admin/routers/${id}/downstream-mikrotiks/discover`,
    routerTrackRuntimePeer: (id: string, peerId: string) => `/api/admin/routers/${id}/wireguard/runtime-peers/${encodeURIComponent(peerId)}/track`,
    createRouter: "/api/admin/routers",
    routerOnboardingClaims: "/api/admin/routers/onboarding/claims",
    routerOnboardingClaimAdopt: (id: string) => `/api/admin/routers/onboarding/claims/${id}/adopt`,
    routerOnboardingClaimCancel: (id: string) => `/api/admin/routers/onboarding/claims/${id}/cancel`,
    routerDiscoveryScan: "/api/admin/routers/discovery/scan",
    routerDiscoveryResults: "/api/admin/routers/discovery/results",
    routerDiscoveryVerify: "/api/admin/routers/discovery/verify",
    routerDiscoveryImport: "/api/admin/routers/discovery/import",
    disableRouter: (id: string) => `/api/admin/routers/${id}/disable`,
    reactivateRouter: (id: string) => `/api/admin/routers/${id}/reactivate`,
    reprovisionRouter: (id: string) => `/api/admin/routers/${id}/reprovision`,
    regenerateRouterSetup: (id: string) => `/api/admin/routers/${id}/regenerate-setup`,
    resetRouterPeer: (id: string) => `/api/admin/routers/${id}/reset-peer`,
    reassignRouterPorts: (id: string) => `/api/admin/routers/${id}/reassign-ports`,
    moveRouterServer: (id: string) => `/api/admin/routers/${id}/move-server`,
    markRouterReviewed: (id: string) => `/api/admin/routers/${id}/mark-reviewed`,
    rebootRouter: (id: string) => `/api/admin/routers/${id}/reboot`,
    pingRouter: (id: string) => `/api/admin/routers/${id}/ping`,
    runRouterCommand: (id: string) => `/api/admin/routers/${id}/command`,
    routerLiveHealth: (id: string) => `/api/admin/routers/${id}/live-health`,
    removeRouterFlag: (id: string, flagId: string) => `/api/admin/routers/${id}/flags/${flagId}`,
    deleteRouter: (id: string) => `/api/admin/routers/${id}`,
    vpnServersStats: "/api/admin/vpn-servers/stats",
    vpnServers: "/api/admin/vpn-servers",
    vpnServerDetail: (id: string) => `/api/admin/vpn-servers/${id}`,
    vpnServerHealth: (id: string) => `/api/admin/vpn-servers/${id}/health`,
    vpnServerRouters: (id: string) => `/api/admin/vpn-servers/${id}/routers`,
    vpnServerPeers: (id: string) => `/api/admin/vpn-servers/${id}/peers`,
    vpnServerTraffic: (id: string) => `/api/admin/vpn-servers/${id}/traffic`,
    vpnServerActivity: (id: string) => `/api/admin/vpn-servers/${id}/activity`,
    vpnServerDiagnostics: (id: string) => `/api/admin/vpn-servers/${id}/diagnostics`,
    vpnServerNotes: (id: string) => `/api/admin/vpn-servers/${id}/notes`,
    vpnServerFlags: (id: string) => `/api/admin/vpn-servers/${id}/flags`,
    addVpnServer: "/api/admin/vpn-servers",
    disableVpnServer: (id: string) => `/api/admin/vpn-servers/${id}/disable`,
    reactivateVpnServer: (id: string) => `/api/admin/vpn-servers/${id}/reactivate`,
    enableServerMaintenance: (id: string) => `/api/admin/vpn-servers/${id}/maintenance`,
    clearServerMaintenance: (id: string) => `/api/admin/vpn-servers/${id}/maintenance/clear`,
    migrateServerRouters: (id: string) => `/api/admin/vpn-servers/${id}/migrate-routers`,
    restartServerVpn: (id: string) => `/api/admin/vpn-servers/${id}/restart-vpn`,
    reconcileVpnServer: (id: string) => `/api/admin/vpn-servers/${id}/reconcile`,
    markVpnServerReviewed: (id: string) => `/api/admin/vpn-servers/${id}/mark-reviewed`,
    removeVpnServerFlag: (id: string, flagId: string) => `/api/admin/vpn-servers/${id}/flags/${flagId}`,
    monitoringOverview: "/api/admin/monitoring/overview",
    monitoringTrends: "/api/admin/monitoring/trends",
    monitoringActivity: "/api/admin/monitoring/activity",
    monitoringDiagnostics: "/api/admin/monitoring/diagnostics",
    monitoringRouterSummary: "/api/admin/monitoring/routers/summary",
    monitoringRoutersUnhealthy: "/api/admin/monitoring/routers/unhealthy",
    monitoringRoutersOffline: "/api/admin/monitoring/routers/offline",
    monitoringRoutersProvisioningIssues: "/api/admin/monitoring/routers/provisioning-issues",
    monitoringRoutersStale: "/api/admin/monitoring/routers/stale",
    monitoringVpnServerSummary: "/api/admin/monitoring/vpn-servers/summary",
    monitoringVpnServersUnhealthy: "/api/admin/monitoring/vpn-servers/unhealthy",
    monitoringVpnServersOverloaded: "/api/admin/monitoring/vpn-servers/overloaded",
    monitoringVpnServersStale: "/api/admin/monitoring/vpn-servers/stale",
    monitoringPeerSummary: "/api/admin/monitoring/peers/summary",
    monitoringPeersStale: "/api/admin/monitoring/peers/stale",
    monitoringPeersUnhealthy: "/api/admin/monitoring/peers/unhealthy",
    monitoringTrafficSummary: "/api/admin/monitoring/traffic/summary",
    monitoringTrafficTrends: "/api/admin/monitoring/traffic/trends",
    monitoringTrafficTopRouters: "/api/admin/monitoring/traffic/top-routers",
    monitoringTrafficTopServers: "/api/admin/monitoring/traffic/top-servers",
    monitoringCustomerImpact: "/api/admin/monitoring/customers/impact",
    monitoringAffectedCustomers: "/api/admin/monitoring/customers/affected",
    monitoringProvisioningSummary: "/api/admin/monitoring/provisioning/summary",
    monitoringProvisioningTrends: "/api/admin/monitoring/provisioning/trends",
    monitoringProvisioningFailures: "/api/admin/monitoring/provisioning/failures",
    monitoringIncidents: "/api/admin/monitoring/incidents",
    monitoringIncidentDetail: (id: string) => `/api/admin/monitoring/incidents/${id}`,
    monitoringIncidentNotes: (id: string) => `/api/admin/monitoring/incidents/${id}/notes`,
    acknowledgeMonitoringIncident: (id: string) => `/api/admin/monitoring/incidents/${id}/acknowledge`,
    resolveMonitoringIncident: (id: string) => `/api/admin/monitoring/incidents/${id}/resolve`,
    markMonitoringIncidentReviewed: (id: string) => `/api/admin/monitoring/incidents/${id}/mark-reviewed`,
    billingOverview: "/api/admin/billing/overview",
    billingReadiness: "/api/admin/billing/readiness",
    referralsOverview: "/api/admin/referrals/overview",
    referrals: "/api/admin/referrals",
    approveReferral: (id: string) => `/api/admin/referrals/${id}/approve`,
    rejectReferral: (id: string) => `/api/admin/referrals/${id}/reject`,
    offerReferral: (id: string) => `/api/admin/referrals/${id}/offer`,
    markReferralPaid: (id: string) => `/api/admin/referrals/${id}/mark-paid`,
    billingAnalytics: "/api/admin/billing/analytics",
    billingActivity: "/api/admin/billing/activity",
    billingRisk: "/api/admin/billing/risk",
    billingSubscriptions: "/api/admin/billing/subscriptions",
    billingSubscriptionDetail: (id: string) => `/api/admin/billing/subscriptions/${id}`,
    billingRouterSubscription: (routerId: string) => `/api/admin/billing/routers/${routerId}/subscription`,
    billingAccountOverview: (id: string) => `/api/admin/billing/accounts/${id}/overview`,
    billingAccountEntitlements: (id: string) => `/api/admin/billing/accounts/${id}/entitlements`,
    billingAccountBillableRouters: (id: string) => `/api/admin/billing/accounts/${id}/billable-routers`,
    billingAccountActivity: (id: string) => `/api/admin/billing/accounts/${id}/activity`,
    billingInvoices: "/api/admin/billing/invoices",
    createInvoice: "/api/admin/billing/invoices",
    billingInvoiceDetail: (id: string) => `/api/admin/billing/invoices/${id}`,
    downloadInvoicePdf: (id: string) => `/api/admin/billing/invoices/${id}/pdf`,
    billingAccountInvoices: (id: string) => `/api/admin/billing/accounts/${id}/invoices`,
    billingPayments: "/api/admin/billing/payments",
    recordPayment: "/api/admin/billing/payments",
    billingPaymentDetail: (id: string) => `/api/admin/billing/payments/${id}`,
    billingAccountPayments: (id: string) => `/api/admin/billing/accounts/${id}/payments`,
    issueRefund: "/api/admin/billing/refunds",
    billingRevenueReport: "/api/admin/billing/reports/revenue",
    billingOutstandingReport: "/api/admin/billing/reports/outstanding",
    billingTrials: "/api/admin/billing/trials",
    billingNotes: (id: string) => `/api/admin/billing/accounts/${id}/notes`,
    billingFlags: (id: string) => `/api/admin/billing/accounts/${id}/flags`,
    billingExtendTrial: (id: string) => `/api/admin/billing/accounts/${id}/extend-trial`,
    billingMarkReviewed: (id: string) => `/api/admin/billing/accounts/${id}/mark-reviewed`,
    billingSuspend: (id: string) => `/api/admin/billing/accounts/${id}/suspend`,
    billingReactivate: (id: string) => `/api/admin/billing/accounts/${id}/reactivate`,
    billingResendInvoice: (id: string) => `/api/admin/billing/accounts/${id}/resend-invoice`,
    billingApplyGracePeriod: (id: string) => `/api/admin/billing/accounts/${id}/apply-grace-period`,
    billingRemoveGracePeriod: (id: string) => `/api/admin/billing/accounts/${id}/remove-grace-period`,
    billingAddBalance: (id: string) => `/api/admin/billing/accounts/${id}/add-balance`,
    billingRemoveFlag: (id: string, flagId: string) => `/api/admin/billing/accounts/${id}/flags/${flagId}`,
    billingEnforce: "/api/admin/billing/enforce",
    billingSubscriptionSuspend: (id: string) => `/api/admin/billing/subscriptions/${id}/suspend`,
    billingSubscriptionReactivate: (id: string) => `/api/admin/billing/subscriptions/${id}/reactivate`,
    supportOverview: "/api/admin/support/overview",
    supportAnalytics: "/api/admin/support/analytics",
    supportTickets: "/api/admin/support/tickets",
    createTicket: "/api/admin/support/tickets",
    supportTicketDetail: (id: string) => `/api/admin/support/tickets/${id}`,
    supportTicketActivity: (id: string) => `/api/admin/support/tickets/${id}/activity`,
    supportTicketMessages: (id: string) => `/api/admin/support/tickets/${id}/messages`,
    supportTicketContext: (id: string) => `/api/admin/support/tickets/${id}/context`,
    supportTicketNotes: (id: string) => `/api/admin/support/tickets/${id}/notes`,
    supportTicketFlags: (id: string) => `/api/admin/support/tickets/${id}/flags`,
    supportAssignTicket: (id: string) => `/api/admin/support/tickets/${id}/assign`,
    supportReassignTicket: (id: string) => `/api/admin/support/tickets/${id}/reassign`,
    supportUnassignTicket: (id: string) => `/api/admin/support/tickets/${id}/unassign`,
    supportTicketStatus: (id: string) => `/api/admin/support/tickets/${id}/status`,
    supportTicketPriority: (id: string) => `/api/admin/support/tickets/${id}/priority`,
    supportTicketCategory: (id: string) => `/api/admin/support/tickets/${id}/category`,
    supportEscalateTicket: (id: string) => `/api/admin/support/tickets/${id}/escalate`,
    supportDeEscalateTicket: (id: string) => `/api/admin/support/tickets/${id}/de-escalate`,
    supportReopenTicket: (id: string) => `/api/admin/support/tickets/${id}/reopen`,
    supportResolveTicket: (id: string) => `/api/admin/support/tickets/${id}/resolve`,
    supportCloseTicket: (id: string) => `/api/admin/support/tickets/${id}/close`,
    supportReplyToTicket: (id: string) => `/api/admin/support/tickets/${id}/reply`,
    supportMarkTicketReviewed: (id: string) => `/api/admin/support/tickets/${id}/mark-reviewed`,
    supportAssignTicketTeam: (id: string) => `/api/admin/support/tickets/${id}/team`,
    supportQueuesUnassigned: "/api/admin/support/queues/unassigned",
    supportQueuesEscalated: "/api/admin/support/queues/escalated",
    supportQueuesStale: "/api/admin/support/queues/stale",
    supportQueuesByAssignee: "/api/admin/support/queues/by-assignee",
    supportQueuesByTeam: "/api/admin/support/queues/by-team",
    supportAssigneeTickets: (id: string) => `/api/admin/support/assignees/${id}/tickets`,
    supportAgents: "/api/admin/support/agents",
    supportRemoveFlag: (ticketId: string, flagId: string) => `/api/admin/support/tickets/${ticketId}/flags/${flagId}`,
    logsActivity: "/api/admin/logs/activity",
    exportActivityLogs: "/api/admin/logs/activity/export",
    logsActivityDetail: (id: string) => `/api/admin/logs/activity/${id}`,
    logsSearch: "/api/admin/logs/search",
    logsUserTimeline: (id: string) => `/api/admin/logs/users/${id}/timeline`,
    logsRouterTimeline: (id: string) => `/api/admin/logs/routers/${id}/timeline`,
    logsVpnServerTimeline: (id: string) => `/api/admin/logs/vpn-servers/${id}/timeline`,
    logsBillingTimeline: (id: string) => `/api/admin/logs/billing/accounts/${id}/timeline`,
    logsSupportTicketTimeline: (id: string) => `/api/admin/logs/support/tickets/${id}/timeline`,
    logsIncidentTimeline: (id: string) => `/api/admin/logs/incidents/${id}/timeline`,
    auditTrail: "/api/admin/audit",
    exportAuditTrail: "/api/admin/audit/export",
    auditDetail: (id: string) => `/api/admin/audit/${id}`,
    securityOverview: "/api/admin/security/overview",
    securityEvents: "/api/admin/security/events",
    exportSecurityEvents: "/api/admin/security/events/export",
    securityEventDetail: (id: string) => `/api/admin/security/events/${id}`,
    suspiciousSecurityActivity: "/api/admin/security/suspicious",
    securityReviews: "/api/admin/security/reviews",
    securitySessions: "/api/admin/security/sessions",
    userSecuritySessions: (id: string) => `/api/admin/security/users/${id}/sessions`,
    revokeSecuritySession: (id: string) => `/api/admin/security/sessions/${id}/revoke`,
    revokeAllUserSecuritySessions: (id: string) => `/api/admin/security/users/${id}/revoke-all-sessions`,
    userSecuritySummary: (id: string) => `/api/admin/security/users/${id}/summary`,
    userSecurityEvents: (id: string) => `/api/admin/security/users/${id}/events`,
    userSecurityReviews: (id: string) => `/api/admin/security/users/${id}/reviews`,
    markUserSecurityReviewed: (id: string) => `/api/admin/security/users/${id}/mark-reviewed`,
    userSecurityNotes: (id: string) => `/api/admin/security/users/${id}/notes`,
    acknowledgeSecurityEvent: (id: string) => `/api/admin/security/events/${id}/acknowledge`,
    resolveSecurityEvent: (id: string) => `/api/admin/security/events/${id}/resolve`,
    markSecurityEventReviewed: (id: string) => `/api/admin/security/events/${id}/mark-reviewed`,
    securityEventNotes: (id: string) => `/api/admin/security/events/${id}/notes`,
    platformConfig: "/api/admin/settings/platform",
    resellers: "/api/admin/resellers",
    adminAccounts: "/api/admin/management/admins",
    adminAccountDetail: (id: string) => `/api/admin/management/admins/${id}`,
    deactivateAdminAccount: (id: string) => `/api/admin/management/admins/${id}/deactivate`,
    activateAdminAccount: (id: string) => `/api/admin/management/admins/${id}/activate`,
    servicePlans: "/api/admin/service-plans",
    servicePlanDetail: (id: string) => `/api/admin/service-plans/${id}`,
    deactivateServicePlan: (id: string) => `/api/admin/service-plans/${id}/deactivate`,
    planVouchersGenerate: (planId: string) => `/api/admin/service-plans/${planId}/vouchers/generate`,
    planVouchers: (planId: string) => `/api/admin/service-plans/${planId}/vouchers`,
    exportVouchers: "/api/admin/service-plans/vouchers/export",
    revokeVoucher: (code: string) => `/api/admin/service-plans/vouchers/${code}/revoke`,
  },
  users: "/api/users",
  routers: "/api/routers",
  clients: "/api/clients",
  clientDetail: (name: string) => `/api/clients/${encodeURIComponent(name)}`,
  clientConfig: (name: string) => `/api/clients/${encodeURIComponent(name)}/config`,
  clientAutoconfig: (name: string) => `/api/clients/${encodeURIComponent(name)}/autoconfig`,
  clientMikrotikScript: (name: string) => `/api/clients/${encodeURIComponent(name)}/mikrotik`,
  pingClient: (name: string) => `/api/clients/${encodeURIComponent(name)}/ping`,
  createClient: "/api/clients",
  updateClient: (name: string) => `/api/clients/${encodeURIComponent(name)}`,
  regenerateClientKeys: (name: string) => `/api/clients/${encodeURIComponent(name)}/regenerate`,
  enableClient: (name: string) => `/api/clients/${encodeURIComponent(name)}/enable`,
  disableClient: (name: string) => `/api/clients/${encodeURIComponent(name)}/disable`,
  deleteClient: (name: string) => `/api/clients/${encodeURIComponent(name)}`,
  bulkDeleteClients: "/api/clients/bulk-delete",
  billing: "/api/billing",
  payments: {
    mpesaInitiate: "/api/payments/mpesa/initiate",
    mpesaQuery: "/api/payments/mpesa/query",
  },
  logs: "/api/logs",
  support: "/api/support",
  settings: "/api/settings",
} as const;
