export const endpoints = {
  auth: {
    login: "/api/auth/login",
    me: "/api/auth/me",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
    logout: "/api/auth/logout",
    refresh: "/api/auth/refresh",
  },
  admin: {
    dashboard: "/api/admin/stats",
    proxyStatus: "/api/admin/proxy/status",
    usersStats: "/api/admin/users/stats",
    users: "/api/admin/users",
    userDetail: (id: string) => `/api/admin/users/${id}`,
    userServices: (id: string) => `/api/admin/users/${id}/services`,
    userRouters: (id: string) => `/api/admin/users/${id}/routers`,
    userBilling: (id: string) => `/api/admin/users/${id}/billing`,
    userActivity: (id: string) => `/api/admin/users/${id}/activity`,
    userSecurity: (id: string) => `/api/admin/users/${id}/security`,
    userSupport: (id: string) => `/api/admin/users/${id}/support`,
    userNotes: (id: string) => `/api/admin/users/${id}/notes`,
    userFlags: (id: string) => `/api/admin/users/${id}/flags`,
    suspendUser: (id: string) => `/api/admin/users/${id}/suspend`,
    reactivateUser: (id: string) => `/api/admin/users/${id}/reactivate`,
    verifyUser: (id: string) => `/api/admin/users/${id}/verify`,
    resendVerification: (id: string) => `/api/admin/users/${id}/resend-verification`,
    sendPasswordReset: (id: string) => `/api/admin/users/${id}/send-password-reset`,
    forceLogoutUser: (id: string) => `/api/admin/users/${id}/force-logout`,
    extendUserTrial: (id: string) => `/api/admin/users/${id}/extend-trial`,
    addUserNote: (id: string) => `/api/admin/users/${id}/notes`,
    flagUser: (id: string) => `/api/admin/users/${id}/flags`,
    removeUserFlag: (id: string, flagId: string) => `/api/admin/users/${id}/flags/${flagId}`,
    routerStats: "/api/admin/routers/stats",
    routers: "/api/admin/routers",
    routerDetail: (id: string) => `/api/admin/routers/${id}`,
    routerConnectivity: (id: string) => `/api/admin/routers/${id}/connectivity`,
    routerPorts: (id: string) => `/api/admin/routers/${id}/ports`,
    routerMonitoring: (id: string) => `/api/admin/routers/${id}/monitoring`,
    routerActivity: (id: string) => `/api/admin/routers/${id}/activity`,
    routerProvisioning: (id: string) => `/api/admin/routers/${id}/provisioning`,
    routerDiagnostics: (id: string) => `/api/admin/routers/${id}/diagnostics`,
    routerNotes: (id: string) => `/api/admin/routers/${id}/notes`,
    routerFlags: (id: string) => `/api/admin/routers/${id}/flags`,
    disableRouter: (id: string) => `/api/admin/routers/${id}/disable`,
    reactivateRouter: (id: string) => `/api/admin/routers/${id}/reactivate`,
    reprovisionRouter: (id: string) => `/api/admin/routers/${id}/reprovision`,
    regenerateRouterSetup: (id: string) => `/api/admin/routers/${id}/regenerate-setup`,
    resetRouterPeer: (id: string) => `/api/admin/routers/${id}/reset-peer`,
    reassignRouterPorts: (id: string) => `/api/admin/routers/${id}/reassign-ports`,
    moveRouterServer: (id: string) => `/api/admin/routers/${id}/move-server`,
    markRouterReviewed: (id: string) => `/api/admin/routers/${id}/mark-reviewed`,
    removeRouterFlag: (id: string, flagId: string) => `/api/admin/routers/${id}/flags/${flagId}`,
    deleteRouter: (id: string) => `/api/admin/routers/${id}`,
  },
  users: "/api/users",
  routers: "/api/routers",
  clients: "/api/clients",
  billing: "/api/billing",
  logs: "/api/logs",
  support: "/api/support",
  settings: "/api/settings",
} as const;
