import { permissions } from "@/lib/permissions/permissions";
import { roles, type Role } from "@/lib/permissions/roles";

export const roleAbilities: Record<Role, string[]> = {
  [roles.superAdmin]: Object.values(permissions),
  [roles.networkAdmin]: [
    permissions.dashboardView,
    permissions.routersView,
    permissions.routersManage,
    permissions.routersLiveOps,
    permissions.vpnServersView,
    permissions.vpnServersManage,
    permissions.monitoringView,
    permissions.logsView,
    permissions.logsExport,
    permissions.settingsView,
    permissions.servicePlansView,
    permissions.servicePlansManage,
    permissions.supportView,
    permissions.supportReply,
  ],
  [roles.supportAdmin]: [
    permissions.dashboardView,
    permissions.usersView,
    permissions.usersManage,
    permissions.supportView,
    permissions.supportManage,
    permissions.supportReply,
    permissions.logsView,
    permissions.settingsView,
    permissions.routersView,
  ],
  [roles.billingAdmin]: [
    permissions.dashboardView,
    permissions.billingView,
    permissions.billingManage,
    permissions.billingRecordPayment,
    permissions.billingCreateInvoice,
    permissions.billingExport,
    permissions.usersView,
    permissions.logsView,
    permissions.settingsView,
    permissions.supportView,
    permissions.supportReply,
  ],
  [roles.readOnly]: [
    permissions.dashboardView,
    permissions.routersView,
    permissions.vpnServersView,
    permissions.monitoringView,
    permissions.usersView,
    permissions.billingView,
    permissions.logsView,
    permissions.supportView,
    permissions.settingsView,
    permissions.servicePlansView,
  ],
};
