export const permissions = {
  dashboardView: "dashboard:view",
  usersView: "users:view",
  usersManage: "users:manage",
  usersDelete: "users:delete",
  routersView: "routers:view",
  routersManage: "routers:manage",
  routersLiveOps: "routers:live_ops",
  routersRunCommand: "routers:run_command",
  vpnServersView: "vpn_servers:view",
  vpnServersManage: "vpn_servers:manage",
  monitoringView: "monitoring:view",
  billingView: "billing:view",
  billingManage: "billing:manage",
  billingRecordPayment: "billing:record_payment",
  billingCreateInvoice: "billing:create_invoice",
  billingIssueRefund: "billing:issue_refund",
  billingExport: "billing:export",
  logsView: "logs:view",
  logsExport: "logs:export",
  logsManage: "logs:manage",
  supportView: "support:view",
  supportManage: "support:manage",
  supportReply: "support:reply",
  settingsView: "settings:view",
  settingsManage: "settings:manage",
  servicePlansView: "service_plans:view",
  servicePlansManage: "service_plans:manage",
} as const;

export type Permission = (typeof permissions)[keyof typeof permissions];
