import {
  Activity,
  BadgeCheck,
  CircleAlert,
  CreditCard,
  FileText,
  LayoutDashboard,
  LifeBuoy,
  Router,
  Server,
  ShieldAlert,
  Settings,
  StickyNote,
  UserCheck,
  UserCog,
  UserMinus,
  Users,
  UsersRound,
} from "lucide-react";
import { appRoutes } from "@/config/routes";
import { permissions } from "@/lib/permissions/permissions";

export const navigationItems = [
  { label: "Dashboard", icon: LayoutDashboard, path: appRoutes.dashboard, permission: permissions.dashboardView },
  {
    label: "User Management",
    icon: UsersRound,
    path: appRoutes.usersOverview,
    permission: permissions.usersView,
    children: [
      { label: "Overview", icon: UserCog, path: appRoutes.usersOverview },
      { label: "All Users", icon: Users, path: appRoutes.usersAll },
      { label: "Active Users", icon: UserCheck, path: appRoutes.usersActive },
      { label: "Trial Users", icon: BadgeCheck, path: appRoutes.usersTrials },
      { label: "Suspended Users", icon: UserMinus, path: appRoutes.usersSuspended },
      { label: "Verification Queue", icon: BadgeCheck, path: appRoutes.usersVerificationQueue },
      { label: "Billing Risk", icon: CreditCard, path: appRoutes.usersBillingRisk },
      { label: "Security Review", icon: ShieldAlert, path: appRoutes.usersSecurityReview },
      { label: "Support Impact", icon: CircleAlert, path: appRoutes.usersSupportImpact },
      { label: "Internal Notes / Flags", icon: StickyNote, path: appRoutes.usersInternalNotes },
    ],
  },
  {
    label: "Router Management",
    icon: Router,
    path: appRoutes.routersOverview,
    permission: permissions.routersView,
    children: [
      { label: "Overview", icon: Router, path: appRoutes.routersOverview },
      { label: "All Routers", icon: Router, path: appRoutes.routersAll },
      { label: "Online Routers", icon: BadgeCheck, path: appRoutes.routersOnline },
      { label: "Offline Routers", icon: CircleAlert, path: appRoutes.routersOffline },
      { label: "Provisioning Queue", icon: FileText, path: appRoutes.routersProvisioningQueue },
      { label: "Unhealthy Tunnels", icon: ShieldAlert, path: appRoutes.routersUnhealthyTunnels },
      { label: "Port Mapping Issues", icon: Activity, path: appRoutes.routersPortMappingIssues },
      { label: "Server Assignment", icon: Server, path: appRoutes.routersServerAssignment },
      { label: "Diagnostics & Review", icon: ShieldAlert, path: appRoutes.routersDiagnosticsReview },
      { label: "Notes / Flags", icon: StickyNote, path: appRoutes.routersNotesFlags },
    ],
  },
  { label: "VPN Servers", icon: Server, path: appRoutes.vpnServers, permission: permissions.vpnServersView },
  { label: "Monitoring", icon: Activity, path: appRoutes.monitoring, permission: permissions.monitoringView },
  {
    label: "Billing",
    icon: CreditCard,
    path: appRoutes.billing,
    permission: permissions.billingView,
    children: [
      { label: "Invoices", path: appRoutes.billingInvoices },
      { label: "Subscriptions", path: appRoutes.billingSubscriptions },
    ],
  },
  {
    label: "Logs",
    icon: FileText,
    path: appRoutes.logs,
    permission: permissions.logsView,
    children: [
      { label: "Activity", path: appRoutes.activityLogs },
      { label: "Security", path: appRoutes.securityLogs },
    ],
  },
  { label: "Support", icon: LifeBuoy, path: appRoutes.support, permission: permissions.supportView },
  {
    label: "Settings",
    icon: Settings,
    path: appRoutes.settings,
    permission: permissions.settingsView,
    children: [
      { label: "Profile", path: appRoutes.settings },
      { label: "Security", path: appRoutes.settingsSecurity },
      { label: "System", path: appRoutes.settingsSystem },
    ],
  },
] as const;
