import {
  Activity,
  BadgeCheck,
  CircleAlert,
  CreditCard,
  FileText,
  LayoutDashboard,
  LifeBuoy,
  Receipt,
  Router,
  Server,
  ShieldAlert,
  Settings,
  StickyNote,
  UserCheck,
  UserCog,
  UserMinus,
  Users,
  UsersRound,
  Wallet,
} from "lucide-react";
import { appRoutes } from "@/config/routes";
import { permissions } from "@/lib/permissions/permissions";

export const navigationItems = [
  { label: "Dashboard", icon: LayoutDashboard, path: appRoutes.dashboard, permission: permissions.dashboardView },
  {
    label: "User Management",
    icon: UsersRound,
    path: appRoutes.usersOverview,
    permission: permissions.usersView,
    children: [
      { label: "Overview", icon: UserCog, path: appRoutes.usersOverview },
      { label: "All Users", icon: Users, path: appRoutes.usersAll },
      { label: "Active Users", icon: UserCheck, path: appRoutes.usersActive },
      { label: "Trial Users", icon: BadgeCheck, path: appRoutes.usersTrials },
      { label: "Suspended Users", icon: UserMinus, path: appRoutes.usersSuspended },
      { label: "Verification Queue", icon: BadgeCheck, path: appRoutes.usersVerificationQueue },
      { label: "Billing Risk", icon: CreditCard, path: appRoutes.usersBillingRisk },
      { label: "Security Review", icon: ShieldAlert, path: appRoutes.usersSecurityReview },
      { label: "Support Impact", icon: CircleAlert, path: appRoutes.usersSupportImpact },
      { label: "Internal Notes / Flags", icon: StickyNote, path: appRoutes.usersInternalNotes },
    ],
  },
  {
    label: "Router Management",
    icon: Router,
    path: appRoutes.routersOverview,
    permission: permissions.routersView,
    children: [
      { label: "Overview", icon: Router, path: appRoutes.routersOverview },
      { label: "All Routers", icon: Router, path: appRoutes.routersAll },
      { label: "Online Routers", icon: BadgeCheck, path: appRoutes.routersOnline },
      { label: "Offline Routers", icon: CircleAlert, path: appRoutes.routersOffline },
      { label: "Provisioning Queue", icon: FileText, path: appRoutes.routersProvisioningQueue },
      { label: "Unhealthy Tunnels", icon: ShieldAlert, path: appRoutes.routersUnhealthyTunnels },
      { label: "Port Mapping Issues", icon: Activity, path: appRoutes.routersPortMappingIssues },
      { label: "Server Assignment", icon: Server, path: appRoutes.routersServerAssignment },
      { label: "Diagnostics & Review", icon: ShieldAlert, path: appRoutes.routersDiagnosticsReview },
      { label: "Notes / Flags", icon: StickyNote, path: appRoutes.routersNotesFlags },
    ],
  },
  {
    label: "VPN Servers",
    icon: Server,
    path: appRoutes.vpnServersOverview,
    permission: permissions.vpnServersView,
    children: [
      { label: "Overview", icon: Server, path: appRoutes.vpnServersOverview },
      { label: "All Servers", icon: Server, path: appRoutes.vpnServersAll },
      { label: "Healthy Servers", icon: BadgeCheck, path: appRoutes.vpnServersHealthy },
      { label: "Unhealthy Servers", icon: CircleAlert, path: appRoutes.vpnServersUnhealthy },
      { label: "Maintenance Mode", icon: Settings, path: appRoutes.vpnServersMaintenance },
      { label: "Overloaded Servers", icon: Activity, path: appRoutes.vpnServersOverloaded },
      { label: "Router Distribution", icon: Router, path: appRoutes.vpnServersRouterDistribution },
      { label: "Peer Health", icon: ShieldAlert, path: appRoutes.vpnServersPeerHealth },
      { label: "Traffic & Load", icon: Activity, path: appRoutes.vpnServersTrafficLoad },
      { label: "Diagnostics & Review", icon: StickyNote, path: appRoutes.vpnServersDiagnosticsReview },
    ],
  },
  {
    label: "Monitoring & Analytics",
    icon: Activity,
    path: appRoutes.monitoringOverview,
    permission: permissions.monitoringView,
    children: [
      { label: "Overview", icon: Activity, path: appRoutes.monitoringOverview },
      { label: "Router Health", icon: Router, path: appRoutes.monitoringRouterHealth },
      { label: "VPN Server Health", icon: Server, path: appRoutes.monitoringVpnServerHealth },
      { label: "Peer / Tunnel Health", icon: ShieldAlert, path: appRoutes.monitoringPeerHealth },
      { label: "Traffic & Bandwidth", icon: Activity, path: appRoutes.monitoringTrafficBandwidth },
      { label: "Customer Impact", icon: Users, path: appRoutes.monitoringCustomerImpact },
      { label: "Provisioning Analytics", icon: BadgeCheck, path: appRoutes.monitoringProvisioningAnalytics },
      { label: "Incidents & Alerts", icon: CircleAlert, path: appRoutes.monitoringIncidentsAlerts },
      { label: "Diagnostics", icon: StickyNote, path: appRoutes.monitoringDiagnostics },
      { label: "Activity Feed", icon: FileText, path: appRoutes.monitoringActivityFeed },
    ],
  },
  {
    label: "Billing & Subscriptions",
    icon: CreditCard,
    path: appRoutes.billingOverview,
    permission: permissions.billingView,
    children: [
      { label: "Overview", icon: CreditCard, path: appRoutes.billingOverview },
      { label: "Subscriptions", icon: FileText, path: appRoutes.billingSubscriptions },
      { label: "Trial Accounts", icon: BadgeCheck, path: appRoutes.billingTrials },
      { label: "Active Paid", icon: Wallet, path: appRoutes.billingActivePaid },
      { label: "Overdue & Risk", icon: CircleAlert, path: appRoutes.billingOverdueRisk },
      { label: "Invoices", icon: Receipt, path: appRoutes.billingInvoices },
      { label: "Payments", icon: Wallet, path: appRoutes.billingPayments },
      { label: "Entitlements", icon: ShieldAlert, path: appRoutes.billingEntitlements },
      { label: "Billing Activity", icon: Activity, path: appRoutes.billingActivity },
      { label: "Notes / Flags", icon: StickyNote, path: appRoutes.billingNotesFlags },
    ],
  },
  {
    label: "Logs",
    icon: FileText,
    path: appRoutes.logs,
    permission: permissions.logsView,
    children: [
      { label: "Activity", path: appRoutes.activityLogs },
      { label: "Security", path: appRoutes.securityLogs },
    ],
  },
  { label: "Support", icon: LifeBuoy, path: appRoutes.support, permission: permissions.supportView },
  {
    label: "Settings",
    icon: Settings,
    path: appRoutes.settings,
    permission: permissions.settingsView,
    children: [
      { label: "Profile", path: appRoutes.settings },
      { label: "Security", path: appRoutes.settingsSecurity },
      { label: "System", path: appRoutes.settingsSystem },
    ],
  },
] as const;
