export const queryKeys = {
  auth: ["auth"] as const,
  me: ["auth", "me"] as const,
  dashboard: ["dashboard"] as const,
  users: ["users"] as const,
  userDetail: (id: string) => ["users", id] as const,
  routers: ["routers"] as const,
  routerDetail: (id: string) => ["routers", id] as const,
  routerMetrics: (id: string, hours: number) => ["routers", id, "metrics", hours] as const,
  hotspotUsers: (routerId: string, filters?: Record<string, unknown>) => ["routers", routerId, "hotspot", "users", filters || {}] as const,
  hotspotUser: (routerId: string, userId: string) => ["routers", routerId, "hotspot", "users", userId] as const,
  hotspotSessions: (routerId: string) => ["routers", routerId, "hotspot", "sessions"] as const,
  hotspotProfiles: (routerId: string) => ["routers", routerId, "hotspot", "profiles"] as const,
  pppoeSecrets: (routerId: string, filters?: Record<string, unknown>) => ["routers", routerId, "pppoe", "secrets", filters || {}] as const,
  pppoeSecret: (routerId: string, secretId: string) => ["routers", routerId, "pppoe", "secrets", secretId] as const,
  pppoeSessions: (routerId: string) => ["routers", routerId, "pppoe", "sessions"] as const,
  pppoeProfiles: (routerId: string) => ["routers", routerId, "pppoe", "profiles"] as const,
  routerQueues: (routerId: string) => ["routers", routerId, "queues"] as const,
  routerQueue: (routerId: string, queueId: string) => ["routers", routerId, "queues", queueId] as const,
  firewallFilterRules: (routerId: string, chain?: string) => ["routers", routerId, "firewall", "filter", chain || "all"] as const,
  firewallNatRules: (routerId: string) => ["routers", routerId, "firewall", "nat"] as const,
  firewallAddressLists: (routerId: string, listName?: string) => ["routers", routerId, "firewall", "address-list", listName || "all"] as const,
  networkDhcpLeases: (routerId: string) => ["routers", routerId, "network", "dhcp-leases"] as const,
  networkWirelessClients: (routerId: string) => ["routers", routerId, "network", "wireless-clients"] as const,
  networkInterfaces: (routerId: string) => ["routers", routerId, "network", "interfaces"] as const,
  routerBackups: (routerId: string, page = 1, limit = 20) => ["routers", routerId, "backups", page, limit] as const,
  routerBackupContent: (routerId: string, backupId: string) => ["routers", routerId, "backups", backupId, "content"] as const,
  routerOnboardingClaims: ["routers", "onboarding-claims"] as const,
  routerDiscoverySessions: ["routers", "discovery-sessions"] as const,
  vpnServers: ["vpn-servers"] as const,
  vpnServerDetail: (id: string) => ["vpn-servers", id] as const,
  monitoring: ["monitoring"] as const,
  billing: ["billing"] as const,
  logs: ["logs"] as const,
  support: ["support"] as const,
  settings: ["settings"] as const,
  servicePlans: ["service-plans"] as const,
  servicePlanDetail: (id: string) => ["service-plans", id] as const,
  vouchers: (planId: string) => ["service-plans", planId, "vouchers"] as const,
};
