export const appRoutes = {
  root: "/",
  auth: "/auth",
  login: "/auth/login",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  dashboard: "/dashboard",
  usersRoot: "/users",
  users: "/users/overview",
  usersOverview: "/users/overview",
  usersAll: "/users/all",
  usersActive: "/users/active",
  usersTrials: "/users/trials",
  usersSuspended: "/users/suspended",
  usersVerificationQueue: "/users/verification-queue",
  usersBillingRisk: "/users/billing-risk",
  usersSecurityReview: "/users/security-review",
  usersSupportImpact: "/users/support-impact",
  usersInternalNotes: "/users/internal-notes",
  userDetail: (id = ":id") => `/users/${id}`,
  routersRoot: "/routers",
  routers: "/routers/overview",
  routersOverview: "/routers/overview",
  routersAll: "/routers/all",
  routersOnline: "/routers/online",
  routersOffline: "/routers/offline",
  routersProvisioningQueue: "/routers/provisioning-queue",
  routersUnhealthyTunnels: "/routers/unhealthy-tunnels",
  routersPortMappingIssues: "/routers/port-mapping-issues",
  routersServerAssignment: "/routers/server-assignment",
  routersDiagnosticsReview: "/routers/diagnostics-review",
  routersNotesFlags: "/routers/notes-flags",
  routerDetail: (id = ":id") => `/routers/${id}`,
  vpnServers: "/vpn-servers",
  vpnServerDetail: (id = ":id") => `/vpn-servers/${id}`,
  monitoring: "/monitoring",
  billing: "/billing",
  billingInvoices: "/billing/invoices",
  billingSubscriptions: "/billing/subscriptions",
  logs: "/logs",
  activityLogs: "/logs/activity",
  securityLogs: "/logs/security",
  support: "/support/tickets",
  supportTicket: (id = ":id") => `/support/tickets/${id}`,
  settings: "/settings/profile",
  settingsSecurity: "/settings/security",
  settingsSystem: "/settings/system",
  forbidden: "/403",
  notFound: "/404",
  serverError: "/500",
  networkError: "/network-error",
} as const;
